# Generated by Django 3.1.4 on 2020-12-29 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_primer',
            field=models.DateField(default=datetime.date, verbose_name='Премьера в мире'),
        ),
    ]
