# Generated by Django 3.1.4 on 2021-01-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201229_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='world_primer',
            field=models.DateField(verbose_name='Премьера в мире'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(verbose_name='Год съёмки'),
        ),
    ]
